// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwwmhjctnrhxwbvvztmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3d21oamN0bnJoeHdidnZ6dG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NDg1NDcsImV4cCI6MjA1MDAyNDU0N30.YhBcW64W8IJQ0uMjBWOU0dBn_ohMCzUAtHDgRmjGjqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);